version: "3.9"

services:
  admin-frontend:
    image: ${IMAGE_TAG}
    ports:
      - "8085:80"
    networks:
      - pms-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  pms-network:
    external: true

